name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        bundle: com.github.matzipan.envoyer.flatpak
        manifest-path: ./envoyer/flatpak.yaml
        cache-key: flatpak-builder-${{ github.sha }}
    # - name: Run tests
    #   working-directory: envoyer
    #   run: cargo test --verbose