name: Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: com.github.matzipan.envoyer.flatpak
          manifest-path: ./envoyer/flatpak.yml
          cache-key: flatpak-builder-${{ github.ref }}